
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.ptoj3ct.telegrambotspring.serialization.UserSerializer

#db related settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tgbot
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver



